spring.application.name=crudrest

server.port=8080

#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost;databaseName=cruddb;encrypt=true;trustServerCertificate=true;
#spring.datasource.url= jdbc:sqlserver://localhost;databaseName=cruddb;
#spring.datasource.username=sa
#spring.datasource.password=@ITB123456

#spring.jpa.database-platform=org.hibernate.dialect.SQLServer2012Dialect

spring.datasource.url=jdbc:h2:file:./cruddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123456

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Indica que as tabelas serao criadas caso nao existam ou caso tenham sua estrutura alterada
spring.jpa.hibernate.ddl-auto=update
#Para mostrar as consultas no console
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.h2.console.enabled=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB



#For a cleaner shutdown, configure your Spring Boot application's application.properties or application.yml file to enable the /shutdown actuator endpoint.
management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=shutdown
#  curl -X POST http://localhost:8081/actuator/shutdown

